### ISSUE TITLE
SFTP connection problems on FireFTP

### ISSUE THREAD

**Issue by v0na** [mimecuvalo/paramikojs#9]
Hi,

I hope this message can deliver to correct people.

I am using latest el-capitan osx on my macbook. Probably that error occurred after than I run some commands on terminal.
I was create ssh keys ssh-keygen and ssh-add commands also I was run ssh-agent..

Now the problem is occurs only while connecting sftp hosts, I can still connecting ftp sites.
I saw that error message on fireftp's console;
![image](https://cloud.githubusercontent.com/assets/20012330/16170429/f9cb5de2-355a-11e6-9beb-d0940df6832d.png)

Thanks in advance.

**Comment by mimecuvalo** [comment]
Thanks for the feedback - I'll take a look.  I've heard multiple reports.  Sorry for the inconvenience in the meantime.

**Comment by mimecuvalo** [comment]
This is fixed in the latest version - sorry for the inconvenience :-/

**Comment by v0na** [comment]
thank you for your fast response and quick fix.
